-- megafunction wizard: %FIR Compiler v12.1%
-- GENERATION: XML

-- ============================================================
-- Megafunction Name(s):
-- 			fir_band_pass_ast
-- ============================================================
-- Generated by FIR Compiler 12.1 [Altera, IP Toolbench 1.3.0 Build 243]
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
-- ************************************************************
-- Copyright (C) 1991-2013 Altera Corporation
-- Any megafunction design, and related net list (encrypted or decrypted),
-- support information, device programming or simulation file, and any other
-- associated documentation or information provided by Altera or a partner
-- under Altera's Megafunction Partnership Program may be used only to
-- program PLD devices (but not masked PLD devices) from Altera.  Any other
-- use of such megafunction design, net list, support information, device
-- programming or simulation file, or any other related documentation or
-- information is prohibited for any other purpose, including, but not
-- limited to modification, reverse engineering, de-compiling, or use with
-- any other silicon devices, unless such use is explicitly licensed under
-- a separate agreement with Altera or a megafunction partner.  Title to
-- the intellectual property, including patents, copyrights, trademarks,
-- trade secrets, or maskworks, embodied in any such megafunction design,
-- net list, support information, device programming or simulation file, or
-- any other related documentation or information provided by Altera or a
-- megafunction partner, remains with Altera, the megafunction partner, or
-- their respective licensors.  No other licenses, including any licenses
-- needed under any third party's intellectual property, are provided herein.

library IEEE;
use IEEE.std_logic_1164.all;

ENTITY fir_band_pass IS
	PORT (
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		ast_sink_data	: IN STD_LOGIC_VECTOR (11 DOWNTO 0);
		ast_sink_valid	: IN STD_LOGIC;
		ast_source_ready	: IN STD_LOGIC;
		ast_sink_error	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		ast_source_data	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		ast_sink_ready	: OUT STD_LOGIC;
		ast_source_valid	: OUT STD_LOGIC;
		ast_source_error	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0)
	);
END fir_band_pass;

ARCHITECTURE SYN OF fir_band_pass IS


	COMPONENT fir_band_pass_ast
	PORT (
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		ast_sink_data	: IN STD_LOGIC_VECTOR (11 DOWNTO 0);
		ast_sink_valid	: IN STD_LOGIC;
		ast_source_ready	: IN STD_LOGIC;
		ast_sink_error	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		ast_source_data	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		ast_sink_ready	: OUT STD_LOGIC;
		ast_source_valid	: OUT STD_LOGIC;
		ast_source_error	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0)
	);

	END COMPONENT;

BEGIN

	fir_band_pass_ast_inst : fir_band_pass_ast
	PORT MAP (
		clk  =>  clk,
		reset_n  =>  reset_n,
		ast_sink_data  =>  ast_sink_data,
		ast_source_data  =>  ast_source_data,
		ast_sink_valid  =>  ast_sink_valid,
		ast_sink_ready  =>  ast_sink_ready,
		ast_source_valid  =>  ast_source_valid,
		ast_source_ready  =>  ast_source_ready,
		ast_sink_error  =>  ast_sink_error,
		ast_source_error  =>  ast_source_error
	);


END SYN;


-- =========================================================
-- FIR Compiler Wizard Data
-- ===============================
-- DO NOT EDIT FOLLOWING DATA
-- @Altera, IP Toolbench@
-- Warning: If you modify this section, FIR Compiler Wizard may not be able to reproduce your chosen configuration.
-- 
-- Retrieval info: <?xml version="1.0"?>
-- Retrieval info: <MEGACORE title="FIR Compiler"  version="12.1"  build="243"  iptb_version="1.3.0 Build 243"  format_version="120" >
-- Retrieval info:  <NETLIST_SECTION class="altera.ipbu.flowbase.netlist.model.FIRModelClass"  active_core="fir_band_pass_ast" >
-- Retrieval info:   <STATIC_SECTION>
-- Retrieval info:    <PRIVATES>
-- Retrieval info:     <NAMESPACE name = "parameterization">
-- Retrieval info:      <PRIVATE name = "use_mem" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_type" value="M512"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "filter_rate" value="Single Rate"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "filter_factor" value="2"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "coefficient_scaling_type" value="Auto"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "coefficient_scaling_factor" value="2663.965303912064"  type="STRING"  enable="0" />
-- Retrieval info:      <PRIVATE name = "coefficient_bit_width" value="11"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "coefficient_binary_point_position" value="0"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "number_of_input_channels" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "input_number_system" value="Signed Binary"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "input_bit_width" value="12"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "input_binary_point_position" value="0"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "output_bit_width_method" value="Actual Coefficients"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "output_number_system" value="Custom Resolution"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "output_bit_width" value="16"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "output_bits_right_of_binary_point" value="16"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "output_bits_removed_from_lsb" value="9"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "output_lsb_remove_type" value="Truncate"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "output_msb_remove_type" value="Truncate"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "flow_control" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "flow_control_input" value="Slave Sink"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "flow_control_output" value="Master Source"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "device_family" value="Cyclone III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "structure" value="Distributed Arithmetic : Fully Parallel Filter"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pipeline_level" value="3"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "clocks_to_compute" value="1"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "number_of_serial_units" value="2"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "data_storage" value="Logic Cells"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "coefficient_storage" value="Logic Cells"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "multiplier_storage" value="Logic Cells"  type="STRING"  enable="0" />
-- Retrieval info:      <PRIVATE name = "force_non_symmetric_structure" value="0"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "coefficients_reload" value="0"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "coefficients_reload_sgl_clock" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "max_clocks_to_compute" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "set_1" value="Low Pass Set, Floating, Band Pass, Hanning, 32, 1.5E8, 1.5E7, 5.5E7, 0, -1.12474E-4, 4.74116E-4, -0.00209712, -0.00527236, 9.87553E-4, -0.00989875, 0.00532489, 0.0263621, 0.0, 0.0480273, 0.0178911, -0.0654593, 0.0137166, -0.180396, -0.232389, 0.384014, 0.384014, -0.232389, -0.180396, 0.0137166, -0.0654593, 0.0178911, 0.0480273, 0.0, 0.0263621, 0.00532489, -0.00989875, 9.87553E-4, -0.00527236, -0.00209712, 4.74116E-4, -1.12474E-4"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "number_of_sets" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "output_full_bit_width" value="25"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "output_full_bits_right_of_binary_point" value="21"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "coefficient_reload_bit_width" value="14"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "logic_cell" value="2584"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "m512" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "m4k" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "m144k" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "m9k" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "m20k" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mlab" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "megaram" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dsp_block" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "input_clock_period" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "output_clock_period" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "throughput" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_units" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen_enable">
-- Retrieval info:      <PRIVATE name = "matlab_enable" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "testbench_enable" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "testbench_simulation_clock_period" value="10.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "language" value="VHDL"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enabled" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen">
-- Retrieval info:      <PRIVATE name = "filename" value="fir_band_pass.vho"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "quartus_settings">
-- Retrieval info:      <PRIVATE name = "DEVICE" value="EP2S60F672I4"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FAMILY" value="Stratix II"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "serializer"/>
-- Retrieval info:    </PRIVATES>
-- Retrieval info:    <FILES/>
-- Retrieval info:    <PORTS/>
-- Retrieval info:    <LIBRARIES/>
-- Retrieval info:   </STATIC_SECTION>
-- Retrieval info:  </NETLIST_SECTION>
-- Retrieval info: </MEGACORE>
-- =========================================================
